import { defineThemeConfig } from './types'

export default defineThemeConfig({
  site: 'https://davidsanluisaguirre.com',
  title: 'David San Luis Aguirre',
  description:
    'Blog personal de David San Luis Aguirre — desarrollo web, proyectos y café de especialidad.',
  author: 'David San Luis',
  navbarItems: [
    { label: 'Blog', href: '/posts', icon: 'tabler--article' },
    { label: 'Projects', href: '/projects', icon: 'tabler--code' },
    { label: 'Cafe', href: '/barista-roadmap', icon: 'tabler--coffee' },
    { label: 'Tags', href: '/tags', icon: 'tabler--tags' },
    { label: 'About', href: '/about', icon: 'tabler--user' }
  ],
  footerItems: [
    {
      icon: 'tabler--brand-github',
      href: 'https://github.com/Davidsmait',
      label: 'Github'
    },
    {
      icon: 'tabler--brand-linkedin',
      href: 'https://www.linkedin.com/in/davidsanluisaguirre',
      label: 'LinkedIn'
    },
    {
      icon: 'tabler--brand-instagram',
      href: 'https://www.instagram.com/davidsanluisaguirre/',
      label: 'Instagram'
    },
    {
      icon: 'tabler--mail',
      href: 'mailto:david_sanluis@outlook.com',
      label: 'Email'
    },
    {
      icon: 'tabler--rss',
      href: '/feed.xml',
      label: 'RSS feed'
    }
  ],

  // optional settings
  locale: 'en',
  mode: 'dark',
  modeToggle: true,
  colorScheme: 'scheme-warm',
  openGraphImage: undefined,
  postsPerPage: 4,
  projectsPerPage: 3,
  scrollProgress: true,
  scrollToTop: true,
  tagIcons: {
    // dev & frameworks
    tailwindcss: 'tabler--brand-tailwind',
    astro: 'tabler--brand-astro',
    angular: 'tabler--brand-angular',
    nextjs: 'tabler--brand-nextjs',
    nestjs: 'tabler--server',
    ionic: 'tabler--device-mobile',
    firebase: 'tabler--flame',
    sqlite: 'tabler--database',
    scala: 'tabler--code',
    pwa: 'tabler--app-window',
    git: 'tabler--git-branch',
    github: 'tabler--brand-github',
    gpg: 'tabler--lock',
    'claude-code': 'tabler--robot',
    ia: 'tabler--brain',
    documentation: 'tabler--book',
    desarrollo: 'tabler--code',
    development: 'tabler--code',
    seguridad: 'tabler--shield',

    // cafe general
    cafe: 'tabler--coffee',
    café: 'tabler--coffee',
    barista: 'tabler--coffee',
    barismo: 'tabler--coffee',
    especialidad: 'tabler--star',
    specialty: 'tabler--star',

    // brewing methods
    espresso: 'tabler--coffee',
    chemex: 'tabler--flask',
    v60: 'tabler--triangle-inverted',
    aeropress: 'tabler--arrow-bar-down',
    'french-press': 'tabler--arrow-bar-down',
    'cold-brew': 'tabler--snowflake',
    'clever-dripper': 'tabler--droplet',
    sifon: 'tabler--flask-2',
    siphon: 'tabler--flask-2',
    'pour-over': 'tabler--droplet',
    dripper: 'tabler--triangle-inverted',
    filtro: 'tabler--filter',
    filter: 'tabler--filter',
    filtration: 'tabler--filter',
    filtrado: 'tabler--filter',
    inmersion: 'tabler--arrow-bar-down',
    immersion: 'tabler--arrow-bar-down',

    // science & technique
    extraccion: 'tabler--chart-line',
    extraction: 'tabler--chart-line',
    molienda: 'tabler--settings',
    grinding: 'tabler--settings',
    grinder: 'tabler--settings',
    tueste: 'tabler--flame',
    roasting: 'tabler--flame',
    ciencia: 'tabler--flask',
    science: 'tabler--flask',
    agua: 'tabler--droplet',
    water: 'tabler--droplet',
    temperatura: 'tabler--temperature',
    temperature: 'tabler--temperature',
    presion: 'tabler--gauge',
    pressure: 'tabler--gauge',
    matematicas: 'tabler--math-function',
    mathematics: 'tabler--math-function',
    fisica: 'tabler--atom',
    physics: 'tabler--atom',
    tds: 'tabler--chart-dots',
    refractometro: 'tabler--chart-dots',
    refractometer: 'tabler--chart-dots',
    medicion: 'tabler--ruler',
    measurement: 'tabler--ruler',

    // tasting & sensory
    catacion: 'tabler--cup',
    cupping: 'tabler--cup',
    tasting: 'tabler--cup',
    sensorial: 'tabler--eye',
    sensory: 'tabler--eye',
    sabores: 'tabler--palette',
    flavors: 'tabler--palette',
    paladar: 'tabler--lollipop',
    palate: 'tabler--lollipop',
    descriptores: 'tabler--list-details',
    descriptors: 'tabler--list-details',

    // latte art
    'latte-art': 'tabler--brush',
    microespuma: 'tabler--ripple',
    microfoam: 'tabler--ripple',
    leche: 'tabler--glass-full',
    milk: 'tabler--glass-full',
    rosetta: 'tabler--leaf',
    tulip: 'tabler--flower',
    tulipan: 'tabler--flower',
    etching: 'tabler--pencil',
    vaporizado: 'tabler--cloud',
    steaming: 'tabler--cloud',

    // origin & business
    origen: 'tabler--map-pin',
    origin: 'tabler--map-pin',
    procesamiento: 'tabler--transform',
    processing: 'tabler--transform',
    productor: 'tabler--plant',
    producer: 'tabler--plant',
    trazabilidad: 'tabler--route',
    traceability: 'tabler--route',
    'comercio-directo': 'tabler--arrows-exchange',
    'direct-trade': 'tabler--arrows-exchange',
    'cadena-suministro': 'tabler--truck',
    'supply-chain': 'tabler--truck',
    negocio: 'tabler--briefcase',
    business: 'tabler--briefcase',
    cafeteria: 'tabler--building-store',
    cafetería: 'tabler--building-store',
    emprendimiento: 'tabler--rocket',
    entrepreneurship: 'tabler--rocket',
    operaciones: 'tabler--settings-2',
    operations: 'tabler--settings-2',
    finanzas: 'tabler--chart-pie',
    finances: 'tabler--chart-pie',

    // career & learning
    sca: 'tabler--certificate',
    cqi: 'tabler--certificate',
    'q-grader': 'tabler--certificate',
    certificación: 'tabler--certificate',
    certification: 'tabler--certificate',
    competencia: 'tabler--trophy',
    competition: 'tabler--trophy',
    wbc: 'tabler--trophy',
    campeonato: 'tabler--trophy',
    championship: 'tabler--trophy',
    carrera: 'tabler--trending-up',
    career: 'tabler--trending-up',
    'marca-personal': 'tabler--user-star',
    'personal-brand': 'tabler--user-star',
    aprendizaje: 'tabler--school',
    entrenamiento: 'tabler--target',
    training: 'tabler--target',
    practica: 'tabler--repeat',
    practice: 'tabler--repeat',
    recetas: 'tabler--notebook',
    recipes: 'tabler--notebook',
    fundamentos: 'tabler--book-2',
    fundamentals: 'tabler--book-2',

    // equipment & maintenance
    equipo: 'tabler--tools',
    equipment: 'tabler--tools',
    mantenimiento: 'tabler--tool',
    maintenance: 'tabler--tool',
    limpieza: 'tabler--wash',
    cleaning: 'tabler--wash',
    kalita: 'tabler--triangle-inverted',
  },
  shikiThemes: {
    light: 'vitesse-light',
    dark: 'vitesse-black'
  }
})
