name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Astro build
        run: npx astro build

      - name: Upload build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: astro-dist
          path: ./dist

      - name: Verify build output
        run: |
          if [ ! -d "./dist" ]; then
            echo "Build failed: 'dist' directory not found"
            exit 1
          fi
          echo "Build completed successfully"
          

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: astro-dist

      - name: Build project
        run: npm run build

      - name: Verify dist directory dist
        run: ls -la dist

      - name: Verify dist directory /dist
        run: ls -la /dist

      - name: Verify dist directory ./dist
        run: ls -la ./dist

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}

